

proceso.1.ip=localhost
proceso.1.puerto=8080
proceso.2.ip=localhost
proceso.2.puerto=8080
proceso.3.ip=localhost
proceso.3.puerto=8080
proceso.4.ip=localhost
proceso.4.puerto=8080
proceso.5.ip=localhost
proceso.5.puerto=8080
proceso.6.ip=localhost
proceso.6.puerto=8080


total.procesos=6